# Generated by Django 4.1.4 on 2022-12-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='grandtotal',
            field=models.IntegerField(default=0),
        ),
    ]
